services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"   
    volumes:
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local
    